### ISSUE TITLE
(Windows) RepoZ is fixed at bottom right

### ISSUE THREAD

**Issue by No3371** [awaescher/RepoZ#154]
My taskbar is anchored to the top of the screen, so I expected to see RepoZ shows relative to the task bar icon, just like how it is in the Mac screenshot shown in the repo, however it sticks to bottom right of the screen.

It's not a big deal, of course, just unexpected UX  😄

**Comment by awaescher** [comment]
This should have been solved with #110.
Would you check if you have an older version?

**Comment by No3371** [comment]
No, I installed it very recently.
I didn't realize that I can reposition it, though. The issue is about that it does not aware where the icon/taskbar is.

**Comment by ZodmanPerth** [comment]
I've looked through the attached issues and I still can't work out how to move the window.  I've been able to resize by dragging the corners and move to different screens with keyboard shortcuts, but how to I move the window out of the bottom right into the center of the screen?
